version: "3.9"

services:
  db:
    image: postgres:17
    container_name: weather-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npx knex migrate:latest && npm start"
    # uncomment below if you want to run in development with live reload (nodemon)
    # command: sh -c "npx knex migrate:latest && npm run dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "5180:80"
    depends_on:
      - app
    restart: unless-stopped

  test:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm test
    env_file:
      - ./server/.env.docker
    depends_on:
      - db

volumes:
  db_data:
    driver: local